experiment_name: "NSFnet_Test"
description: "快速測試配置 - 適用於開發和調試"

network:
  layers: 2
  layers_1: 2
  hidden_size: 20
  hidden_size_1: 10
  first_layer_scale_main: 1.0
  last_layer_scale_main: 0.5
  first_layer_scale_evm: 1.2
  last_layer_scale_evm: 0.1
  evm_output_activation: softplus_cap
  activation_main: laaf
  activation_evm: tanh
  laaf_init_scale: 1.0
  laaf_max_scale: 20.0
  laaf_reg_lambda: 1.0e-4

training:
  N_f: 1000
  batch_size: null
  checkpoint_freq: 50
  log_tips: true
  training_stages:
    - [0.05, 10, 0.001]    # Stage 1: 10 epochs
    - [0.03, 10, 0.0005]   # Stage 2: 10 epochs
  
  # L-BFGS相關配置
  lbfgs:
    enabled_in_distributed: true      # 啟用分佈式L-BFGS
    trigger_window_per_stage: [50, 100, 200]
    min_improve_pct_per_stage: [0.05, 0.02, 0.01]
    ema_gamma: 0.9
    grad_median_abs_thresh: 0.001
    grad_relative_factor: 0.01
    grad_cos_ema_thresh: 0.8
    cooldown_steps: 100
    freeze_evm_during_lbfgs: true
    max_outer_steps: 20
    timeout_seconds: 120
    max_iter: 10
    history_size: 5
    tolerance_grad: 1e-6
    tolerance_change: 1e-7
    line_search_fn: "strong_wolfe"    # 線搜索方法
    early_stop_patience: 5
    early_stop_min_delta: 1e-4
    checkpoint_before_lbfgs: true     # L-BFGS前自動保存

physics:
  Re: 3000
  alpha_evm: 0.03
  beta: 1.0
  bc_weight: 20.0
  eq_weight: 1.0

supervision:
  enabled: true
  data_points: 1  # 测试时使用1个数据点
  data_path: "data/cavity_Re5000_256_Uniform.mat"
  weight: 1.0
  random_seed: 42

system:
  device: "auto"
  precision: "float32"
  tensorboard_enabled: true
  log_level: "DEBUG"
  memory_limit_gb: 2.0
  gradient_clip_norm: 1.0
  memory_cleanup_freq: 10
  epoch_times_limit: 100
